name: nativefier
adopt-info: nativefier
summary: Nativefier is a command-line tool to easily create a “desktop app”
description: |
  Nativefier is a command-line tool to easily create a “desktop app” for any web site with minimal fuss. 
  Apps are wrapped by Electron (which uses Chromium under the hood) in an OS executable (.app, .exe, etc) usable on Windows, macOS and Linux.
  
license: MIT

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: [amd64, armhf, arm64, ppc64el, s390x]
    
assumes:
  - command-chain
  
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-stable
    
apps:
  nativefier: 
    command: bin/nativefier
    command-chain: 
      - bin/homeishome-launch
    plugs:
      - network
      - home  
  
parts: 
  nativefier:
    plugin: npm
    npm-node-version: "18.1.0"    
    source: https://github.com/nativefier/nativefier.git
    source-type: git
    build-snaps:
      - node/18/stable
      
    override-build: |
      npm install --include=dev
      snapcraftctl build

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
    
    stage-packages:
      - imagemagick
      - wine64
      
    stage-snaps:
      - wine-platform-6-stable
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch    
